let object1PathsArray, object2PathsArray, object1ValuesArray, object2ValuesArray, tableOne, tableTwo, flag, searchValue, prevSearch, continueFlag = false;
let selectedValues = [];
let allMoveRightArray = [];
let allMoveLeftArray = [];
let found = 0,
    searchFlag = 0;
let tableHeadings = ["<b>Path</b>", "<b>Value</b>"]
let obj1;
let obj2;
let finalArray1 = [];
let finalArray2 = [];
let startFlag;
let prevclassRowOne;
let prevclassRowTwo;
let path;
let object1Paths = [];
let object2Paths = [];
let object1Values = [];
let object2Values = [];
let diffArray = [];
let tableOneKeyIndex = 1;
let tableTwoKeyIndex = 1;
let diffArrayIndex = -1;
let temparray = [];
let firstTableObj;
let secondTableObj;
let fileOnePresent = false;
let fileTwoPresent = false;
let undoObjects = [];
let redoObjects = [];
let changeIndex = 0;
let allChangesObjects = {};
let undoredoIndex = 0;